run:
  timeout: 5m
  output:
    format: tab
  skip-dirs:
    - vendor

linters-settings:
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.1
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 140
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - experimental
    disabled-checks:
      - wrapperFunc
      - unnamedResult
      - externalErrorReassign
      - whyNoLint

  revive:
    rules:
      - name: exported
        disabled: true

linters:
  enable:
    - bodyclose
    - megacheck
    - revive
    - govet
    - unconvert
    - megacheck
    - gas
    - gocyclo
#    - dupl
    - misspell
    - tparallel
    - unused
    - typecheck
    - ineffassign
    - stylecheck
    - gochecknoinits
    - exportloopref
    - gocritic
    - nakedret
    - gosimple
    - prealloc
    - errcheck
    - nestif
    - noctx
  fast: false
  disable-all: true

issues:
  exclude-rules:
    - text: "at least one file in a package should have a package comment"
      linters:
        - stylecheck
    - text: "should have a package comment, unless it's in another file for this package"
      linters:
        - golint
    - path: _test\.go
      linters:
        - gosec
        - dupl
  exclude-use-default: false
